/* Generated by AN DISI Unibo */ 
package it.unibo.actorusingprolog

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Actorusingprolog ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
			    
			   var CurPlan = ""
			   var CurMove = ""
			   var RSTEP   = false
			   var Goon    = true
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						  clearlog("./logs/app_demoprologqak.log") 	//vedi src/main/resources/logback.xml  
						CommUtils.outblue("$name STARTS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="useLogisticMap", cond=doswitch() )
				}	 
				state("useCellMap") { //this:State
					action { //it:State
						 val CurrentDir = System.getProperty("user.dir");  
						 val CurrentPath = java.nio.file.Paths.get("").toAbsolutePath();  
						CommUtils.outblue("$name useMap")
						solve("consult('${CurrentDir}/src/main/resources/mapProlog.pl')","") //set resVar	
						solve("consult('${CurrentDir}/src/main/resources/maprules.pl')","") //set resVar	
						solve("showCells","") //set resVar	
						CommUtils.outmagenta("$name | execThePlan SOLVE")
						solve("plan(0,0,2,4,down,P)","") //set resVar	
						CommUtils.outblue("$currentSolution")
						 CurPlan = getCurSol("P").toString().replace("[","").replace("]","").replace(",","")  
						CommUtils.outblue("PATH=$CurPlan")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("useLogisticMap") { //this:State
					action { //it:State
						 val CurrentDir = System.getProperty("user.dir");  
						CommUtils.outblue("$name useLogisticMap")
						solve("consult('${CurrentDir}/src/main/resources/logisticmap.pl')","") //set resVar	
						 val N = 10
						 		   val R = 2.0
						 		   val X = 0.5
						 		   //var RES = ""
						solve("mappa_logistica(10,2,'0.5',P)","") //set resVar	
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
