/* Generated by AN DISI Unibo */ 
package it.unibo.a

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import MyCode.*

class A ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						  clearlog("./logs/app_firstprj27.log") 	//vedi src/main/resources/logback.xml  
						CommUtils.outblue("$name STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						CommUtils.outblue("$name - waiting  ...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="doevalvalues",cond=whenRequest("evalfunvalues"))
					transition(edgeName="t01",targetState="doSetParams",cond=whenDispatch("setParams"))
				}	 
				state("doSetParams") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("args(MIN,MAX,DX)"), Term.createTerm("args(MIN,MAX,DX)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Min = payloadArg(0).toDouble()  
								 val Max = payloadArg(1).toDouble()  
								 val Dx  = payloadArg(2).toDouble()  
								 FSinSeries.setParams( Min,Max,Dx  ) 
								CommUtils.outblue("$name - doSetParams done ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="doEvalAvalue",cond=whenEvent("starteval"))
				}	 
				state("doEvalAvalue") { //this:State
					action { //it:State
						 FSinSeries.evalNextPoint()              
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_doEvalAvalue", 
				 	 					  scope, context!!, "local_tout_"+name+"_doEvalAvalue", 10.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="doEvalAvalue",cond=whenTimeout("local_tout_"+name+"_doEvalAvalue"))   
					transition(edgeName="t04",targetState="showValues",cond=whenEvent("stopeval"))
				}	 
				state("showValues") { //this:State
					action { //it:State
						 var Values = FSinSeries.getEvaluedPoints()         
						CommUtils.outgreen("$name - showValues  ")
						 val chartUrl = ChartUtils.buildMapChartUrl("Sin", Values)         
						 ChartUtils.OpenChartInBrowser(chartUrl)                           
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("doevalvalues") { //this:State
					action { //it:State
						emit("serviceworking", "serviceworking(doevalvalues)" ) 
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("args(MIN,MAX,DX)"), Term.createTerm("args(A,B,C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Min = payloadArg(0).toDouble()              
								 val Max = payloadArg(1).toDouble()              
								 val Dx  = payloadArg(2).toDouble()              
								CommUtils.outmagenta("$name - doevalvalues  Min=$Min Max=$Max Dx=$Dx ")
								 val R = "'" + MyCode.FSinSeries.evalSinPoints( Min,Max,Dx ) + "'"  
								CommUtils.outgreen("$name - values: $R  ")
								answer("evalfunvalues", "replyvalues", "values($R)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
			}
		}
} 
