/* Generated by AN DISI Unibo */ 
package it.unibo.mapservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Mapservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						  clearlog("./logs/app_logisticmap.log") 	//vedi src/main/resources/logback.xml  
						CommUtils.outblue("$name STARTS")
						   logger.info(  "actor $name in state:${currentState.stateName}"  )             
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
				state("waitrequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name - waiting for some request ...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="doeval",cond=whenRequest("evallogistic"))
				}	 
				state("doeval") { //this:State
					action { //it:State
						   if( currentMsg.msgId( )== "evallogistic" && checkMsgContent( Term.createTerm("args(R,X1,Y)"), Term.createTerm("args(A,B,C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val R  = payloadArg(0).toDouble()   
								 val X1 = payloadArg(1).toDouble()   
								 val Y  = payloadArg(2).toInt()      
								CommUtils.outmagenta("$name - evallogistic  R=$R X1=$X1 Y=$Y ")
								  MyCode.LogisticSeries.setParameters( R,X1,Y )    
								 val S = "'" + MyCode.LogisticSeries.evalPoints(  ) + "'"  
								CommUtils.outgreen("$name - values S=$S  ")
								forward("showgraph", "values($S)" ,"viewer" ) 
								answer("evallogistic", "replylogistic", "result(done)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
			}
		}
} 
