/* Generated by AN DISI Unibo */ 
package it.unibo.mapservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Mapservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var Parameter_r_wrong  = false 
			   var Parameter_X0_wrong = false 
			   var Parameter_Y_wrong  = false  
			   var R  = 0.0  
			   var X0 = 0.0   
			   var Y  = 0      
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						  clearlog("./logs/app_logisticmap.log") 	//vedi src/main/resources/logback.xml  
						CommUtils.outblue("$name STARTS")
						   logger.info(  "actor $name in state:${currentState.stateName}"  )             
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
				state("waitrequest") { //this:State
					action { //it:State
						 Parameter_r_wrong  = false 
							   Parameter_X0_wrong = false 
							   Parameter_Y_wrong  = false  
						CommUtils.outblue("$name - waiting for some request ...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="checkparams",cond=whenRequest("evallogistic"))
				}	 
				state("checkparams") { //this:State
					action { //it:State
						   if( currentMsg.msgId( )== "evallogistic" && checkMsgContent( Term.createTerm("args(R,X0,Y)"), Term.createTerm("args(A,B,C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 R  = payloadArg(0).toDouble()   
								 X0 = payloadArg(1).toDouble()   
								 Y  = payloadArg(2).toInt()      
								if(  R < 0 || R > 4  
								 ){ Parameter_r_wrong = true  
								CommUtils.outred("$name -  R=$R wrong ")
								}
								if(  X0 < 0 || X0 > 1  
								 ){ Parameter_X0_wrong = true  
								CommUtils.outred("$name -  X0=$X0 wrong ")
								}
								if(  Y < 0  
								 ){ Parameter_Y_wrong = true  
								CommUtils.outred("$name -  Y=$Y wrong ")
								}
								  MyCode.LogisticSeries.setParameters( R,X0,Y )    
								 val S = "'" + MyCode.LogisticSeries.evalPoints(  ) + "'"  
								CommUtils.outgreen("$name - values S=$S  ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doreplywrong", cond=doswitchGuarded({ Parameter_r_wrong || Parameter_X0_wrong || Parameter_Y_wrong  
					}) )
					transition( edgeName="goto",targetState="doeval", cond=doswitchGuarded({! ( Parameter_r_wrong || Parameter_X0_wrong || Parameter_Y_wrong  
					) }) )
				}	 
				state("doreplywrong") { //this:State
					action { //it:State
						answer("evallogistic", "replylogistic", "result(parameter_wrong)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
				state("doeval") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name - evallogistic  R=$R X0=$X0 Y=$Y ")
						  MyCode.LogisticSeries.setParameters( R,X0,Y )    
						 val S = "'" + MyCode.LogisticSeries.evalPoints(  ) + "'"  
						CommUtils.outgreen("$name - values S=$S  ")
						forward("showgraph", "values($S)" ,"viewer" ) 
						answer("evallogistic", "replylogistic", "result(done)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
			}
		}
} 
